name: Harrison Christensen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2509
title: www.HarrisonChristensen.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-70373617-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#d5b79b'
    - '#161b2e'
    - '#69402c'
    - '#6a8399'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
